spring:
  application:
    name: micro-one

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
#  instance:
#    prefer-ip-address: true