spring:
  application:
    name: micro-two

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
#  instance:
#    prefer-ip-address: true